name: solvr_graphics
version: 1.0.0
author: Lars Tackmann <lars@solvr.io>
description: Graphics library
dependencies:
  js: "0.1.0"
  solvr_ast:
    path: ../ast
  solvr_common:
    path: ../common
  solvr_matchers:
    path: ../matchers
dev_dependencies:
  unittest: any
