name: solvr_kernel
version: 1.0.0
author: Lars Tackmann <lars@solvr.io>
description: Math kernel
dependencies:
  solvr_analyzer:
    path: ../analyzer
  solvr_ast:
    path: ../ast
  solvr_common:
    path: ../common
  solvr_matchers:
    path: ../matchers
  solvr_parser:
    path: ../parser
dev_dependencies:
  unittest: any
