name: solvr_kernel
version: 1.0.3
author: Lars Tackmann <lars@solvr.io>
description: Math kernel
dependencies:
  solvr_common:
    path: ../common
  solvr_matchers:
    path: ../matchers
dev_dependencies:
  unittest: any
