name: solvr_common
version: 1.0.0
author: Lars Tackmann <lars@solvr.io>
description: Common utility classes
environment:
  sdk: '>=0.8.5'
dependencies:
  dice: '>=1.4.1'
  log4dart: '>=1.4.10'
  meta: '>=0.8.5'
dev_dependencies:
  unittest: any
