name: solvr_common
version: 1.1.3
author: Lars Tackmann <lars@solvr.io>
description: Common utility classes
dependencies:
  dice: '>=1.2.0'
  log4dart: '>=1.4.8'
  meta: '>=0.7.5'
dev_dependencies:
  unittest: any
