name: solvr_logic
version: 1.0.0
description: Business Logic
dependencies:
  harvest: '>=1.5.1'
  solvr_common:
    path: ../common
  solvr_kernel:
    path: ../kernel
dev_dependencies:
  unittest: any
