name: solvr_webapp
description: The Solvr web application
author: Lars Tackmann <lars@solvr.io>
dependencies:
  solvr_logic:
    path: ../logic
  solvr_ui:
    path: ../ui
dev_dependencies:
  unittest: any
